@url_dev=http://localhost:4052/v1/api/

### signup
POST {{url_dev}}/shop/signup
Content-Type: application/json

{
    "name": "Shop Tips",
    "email": "shoptipjs01@gmail.com",
    "password": "abc123"
}